name: social_share_plugin
description: Social Share to Facebook and Instagram Flutter plugin.
version: 0.3.1+1
homepage: https://romatroskin.github.io/
repository: https://github.com/romatroskin/social_share_plugin.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.8
  http: ^0.12.2
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cygnati.social_share_plugin
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin
