name: social_share_plugin
description: Social Share to Facebook and Instagram Flutter plugin.
version: 0.4.1+3
homepage: https://github.com/romatroskin/social_share_plugin/tree/master/packages/social_share_plugin

environment:
    sdk: ">=3.0.0 <4.0.0"

flutter:
    plugin:
        platforms:
            android:
                default_package: social_share_plugin_android
            ios:
                default_package: social_share_plugin_ios

dependencies:
    flutter:
        sdk: flutter
    social_share_plugin_android: ^0.1.0+1
    social_share_plugin_ios: ^0.1.0+1
    social_share_plugin_platform_interface: ^0.1.0+1

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^0.3.0
    plugin_platform_interface: ^2.0.0
    very_good_analysis: ^5.0.0
